Restyled the page and added the upload icon.
sanger/traction-ui pull request #1064
Opened 2023-02-13 10:01 UTC by stevieing

Closes #

Changes proposed in this pull request:

*
*
* ...

2023-02-24 11:14 UTC, stevieing commented
![Screenshot 2023-02-24 at 11 11 42](https://user-images.githubusercontent.com/519327/221165751-2f9473cc-a930-4182-8795-badf15db94a5.png)

2023-02-27 11:42 UTC, BenTopping commented on src/components/qcResultsUpload/QcResultsUploadForm.vue
> +          <!-- Weird bug - spinner won't show unless button text is two words/ big enough? -->
I think this bug has been fixed. Worth testing and removing comment if it is.

2023-02-27 11:44 UTC, BenTopping commented on src/components/qcResultsUpload/QcResultsUploadForm.vue
> +          <traction-spinner v-show="busy"></traction-spinner>
Its not really an issue but I noticed the spinner does cover the UploadIcon when active. Maybe have the spinner replace the UploadIcon conditionally or might be nice to replace the text and icon conditionally.

2023-02-27 11:45 UTC, BenTopping requested changes
Page looks really good. ESLint has some minor warnings (wondering if we should fail the CI on warnings) and a small detail to check about the spinner.

2023-02-27 14:51 UTC, BenTopping approved these changes

2023-03-02 14:28 UTC, merged