DPL - 716,719 - Ability to select v12 revio and v12 well defaults
sanger/traction-ui pull request #1129
Opened 2023-04-19 10:15 UTC by BenTopping

Closes #1104 #1105

Changes proposed in this pull request:

* Reworked pacbio run well default edit to load fields dynamically

2023-04-24 08:52 UTC, BenTopping commented on src/store/traction/pacbio/runCreate/run.js
> +const smrtLinkVersionDefaultComponents = {
Feel like it might be more sensible to have this data in the component its used it instead of here.

2023-04-24 12:25 UTC, BenTopping commented
> Code looks file but I have tried running it locally. Options change as expected but movie time options don't appear. Also there is no option to select Revio as a Systyem name which might be an idea to add for this story.

Movie times should be there. I had a typo which meant it showed up as Move time which may be where the confusion is. Also system name is pulled from the service so it may be you dont have 12_revio locally or that you dont have it set as active?

2023-04-24 13:42 UTC, stevieing commented
> > Code looks file but I have tried running it locally. Options change as expected but movie time options don't appear. Also there is no option to select Revio as a Systyem name which might be an idea to add for this story.
> 
> @stevieing Movie times should be there. I had a typo which meant it showed up as Move time which may be where the confusion is. Also system name is pulled from the service so it may be you dont have 12_revio locally or that you dont have it set as active?

I was thinking about system name not SMRT Link Version. We have added it to the back end but not the ui.

2023-04-24 14:24 UTC, BenTopping commented
Ah my mistake. I have added it.

2023-04-25 15:10 UTC, stevieing requested changes
For me movie acquisition time still does not have the relevant options? Maybe I am missing something. Also wondering if Include Base Kinetics needs a default but that could wait until UAT.

2023-04-26 09:23 UTC, stevieing approved these changes

2023-04-26 09:54 UTC, merged