DPL-748 update styling for revio
sanger/traction-ui pull request #1211
Opened 2023-06-13 15:20 UTC by StephenHulme

Closes #1133

Changes proposed in this pull request:

- Updates styling, particularly the new/update Runs page
- Repairs new well defaults not being set
- Improved visibility and styling of the message box

<table border="0">
 <tr>
    <td><b style="font-size:30px">Before</b></td>
    <td><b style="font-size:30px">After</b></td>
 </tr>
<tr>
    <td valign="top">
        <img alt="Before" src="https://github.com/sanger/traction-ui/assets/135011085/26df9b2a-e8f7-4d8e-a6b5-6810107b9cef" />
</td><td valign="top">
        <img alt="After" src="https://github.com/sanger/traction-ui/assets/135011085/2be58ba9-b883-4457-ab73-bb72828a281e" />
</td>
</tr>
<tr>
    <td valign="top">
        <img alt="Before" src="https://github.com/sanger/traction-ui/assets/135011085/348898bf-5ff5-4c0e-9298-2e98ec9e9f87" />
</td><td valign="top">
        <img alt="After" src="https://github.com/sanger/traction-ui/assets/135011085/ed0c8e21-9b2f-4a21-9aed-8a64d3b900d3" />
</td>
</tr>
</table>

2023-06-15 13:05 UTC, BenTopping requested changes
Page is looking really good, nice work! Couple comments, mostly syntax related.

2023-06-15 13:05 UTC, BenTopping commented on src/views/pacbio/PacbioRunShow.vue
> +<style scoped>
is there a tailwind alternative we can use?

2023-06-15 13:05 UTC, BenTopping commented on src/store/traction/pacbio/runCreate/getters.js
> +  wells: (state) => state.wells || {},
Can remove this since we no longer have a dynamic summary

2023-06-15 13:05 UTC, BenTopping commented on src/components/pacbio/PacbioRunSummary.vue
> +    wellCount: ({ wells }) => Object.keys(wells).length,
can remove plateCount, wellCount and wells, runItem from mapGetters as they are no longer in use

2023-06-19 10:46 UTC, stevieing approved these changes

2023-06-19 10:58 UTC, BenTopping approved these changes

2023-06-19 10:59 UTC, merged