DPL-939- Pacbio runcreate store change from VueX to Pinia
sanger/traction-ui pull request #1380
Opened 2023-10-20 11:27 UTC by seenanair

This includes following changes

 -  Pinia store creation for Pacbio runcreate - `usePacbioRunCreateStore` (/stores/pacbioRunCreate)
 -  Pinia store creation for root store - `useRootStore` (/stores/index)
 -  Unit test cases added for 
      - usePacbioRunCreateStore
      -  useRootStore
 -  Refactoring of components using pacbioRunCreate store
      - PacbioRunWell
      - PacbioRunPlateItem
      - PacbioRunPlateList
      - PacbioRunShow
      - PacbioRunWellEdit
      - PacbioRunWellDefaultEdit
      - PacbioRunIndex
      - PacbioPoolList
      - PacbioPoolSelectedList
      - PacbioPoolTubeItem
      - PacbioRunInfoEdit
  - Unit test case update for all components using pacbioRunCreate store

2023-10-23 14:02 UTC, stevieing requested changes
Pretty good. Just a couple of things that could be tidied up.

2023-10-23 14:02 UTC, stevieing commented on tests/unit/components/pacbio/PacbioRunInfoEdit.spec.js
> +function mountWithStore(options, props) {
same as above using mountWithStore

2023-10-23 14:02 UTC, stevieing commented on tests/unit/components/pacbio/PacbioRunWellDefaultEdit.spec.js
> +function mountWithStore(options) {
same as above using mountWithStore

2023-10-23 14:02 UTC, stevieing commented on tests/unit/components/pacbio/PacbioRunWellEdit.spec.js
> +function mountWithStore(options) {
same as above using mountWithStore

2023-10-23 14:08 UTC, stevieing reviewed
I have also noticed when I run this locally that the default SMRT Link Versions is not selected. It is there when I run it from develop.

2023-10-23 14:39 UTC, seenanair commented on tests/unit/components/labware/PacbioRunPlateList.spec.js
> +function mountWithStore(options) {
i thought about it, but then I am not sure whether mount supports stubbing dynamic components passed on it.

2023-10-24 10:43 UTC, seenanair commented on tests/unit/components/labware/PacbioRunPlateList.spec.js
> +function mountWithStore(options) {
I had a look into this. We can have a  generic function as follows in tesrHelper. But to optimise the code, we might still require a global function in each components that calls this, with all the custom parameters that are common between test cases. So, I think it doesn't bring much of an advantage. Please share your views.

`function mountWithStore(
  component,
  usePiniaStoreFn,
  storeNames,
  { initialState = {}, stubActions = false, plugins = [] } = {},
  props = {},
  stubs = {},
) {
  const wrapper = mount(component, {
    global: {
      plugins: [
        createTestingPinia({
          initialState,
          stubActions,
          plugins,
        }),
      ],
      stubs,
    },
    router,
    props,
  })
  const store = usePiniaStoreFn()
  return { wrapper, store }
}`

2023-10-24 10:45 UTC, seenanair commented
> I have also noticed when I run this locally that the default SMRT Link Versions is not selected. It is there when I run it from develop.

Just to make sure, I hope you mentioned the 'New run' page?

2023-10-24 13:49 UTC, stevieing approved these changes

2023-10-24 15:10 UTC, merged