DPL-981 store migration from VueX to Pina for ont/runs
sanger/traction-ui pull request #1412
Opened 2023-11-17 16:52 UTC by seenanair

- Created ontRoot, ontRuns store
- Updated stores in components
- Unit test cases added
- Removed Vue stores

2023-11-22 11:47 UTC, stevieing reviewed
Maybe worth going through this and deciding whether we do any of my suggestions.

It is clear that some of this could do with a refactor but it might be worth rolling into another story. One of the things I have noticed is that the ONT runs page performs poorly and this might be part of the reason.

Nothing to do with what you have done! We made the decision at the time to do enough to get it working.

2023-11-22 11:47 UTC, stevieing commented on src/components/ont/runs/ONTFlowcell.vue
> +        if (this.currentRun) {
Not entirely clear what has changed here. 

A way to remove all of the logic would be to create a null object for current run which would return everything you need when currentRun is undefined.

2023-11-22 11:47 UTC, stevieing commented on src/components/ont/runs/ONTFlowcell.vue
> +      const flowcell = ontRunStore.currentRun.flowcell_attributes.find(
same here. If you set currentRun in the store to be something like:

`{  flowcell_attributes: [ { position: 1, tube_barcode: '' }] }`

or you could return a blan flowcell. It is essentially adding a type so you don't need to do lot's of checking.

2023-11-22 11:47 UTC, stevieing commented on src/components/ont/runs/ONTFlowcell.vue
> +      return this.isFlowcellIdExists
Same here. If you make flowcell a type you can delgate the checks to the type itself which means things become more encapsulated. At the moment there are quite a few methods in flowcell which are checking the attributes of flowcell.

2023-11-22 11:47 UTC, stevieing commented on src/stores/ontRoot.js
> +      try {
Same here. Not entirely sure what is happening so worth adding some documentation and again thinking about using types so something is always returned.

2023-11-22 11:47 UTC, stevieing commented on src/stores/ontRuns.js
> +      const flowcell_attributes = run.flowcell_attributes
it looks like createRun and updateRun are also using complex methods to create stuff and doing the same thing which could be resolved by using types.m I am also not sure what fc is.

2023-11-27 08:19 UTC, stevieing requested changes
This is really good. I think there is a lot more we could do with respect to the flowcells e.g. add the colour stuff to the flowcell object itself but I think we can save that for another day.

The only thing I am going to ask you to do is add more documentation the objects and methods. I have referred to a file as an example https://github.com/sanger/traction-ui/blob/develop/src/api/JsonApi.js. It would be great if we could have the params and returnType where possible. This will make it more maintainable.

2023-11-27 09:02 UTC, seenanair commented
> This is really good. I think there is a lot more we could do with respect to the flowcells e.g. add the colour stuff to the flowcell object itself but I think we can save that for another day.
> 
> The only thing I am going to ask you to do is add more documentation the objects and methods. I have referred to a file as an example https://github.com/sanger/traction-ui/blob/develop/src/api/JsonApi.js. It would be great if we could have the params and returnType where possible. This will make it more maintainable.

Thank you @stevieing .
As you mentioned, I thought about moving colours to here, but then I felt it is more conceptually right to allow the component to define it. We can definitely think about it, if we go for another round of optimisation.

For the documentation, I hope you meant utilities/flowCell.js file. I will have a look into the file and add more documentation. 👍

2023-11-27 10:42 UTC, stevieing approved these changes

2023-11-27 10:44 UTC, seenanair commented
@stevieing One request, would you please test the ont run and the 'new run' page manually as well when you get time?

2023-11-28 08:03 UTC, stevieing approved these changes
It might be worth comparing the utilities for ont and pacbio runs. They are essentially doing a lot of the same stuff but slightly differently. Again we can look at this again when we come to refactor ont runs due to the performance issues.

2023-11-28 14:47 UTC, merged