Dpl 1070 library edit volume check
sanger/traction-ui pull request #1631
Opened 2024-04-19 14:15 UTC by seenanair

This PR includes:

- Displaying a "used volume" label when the user edits a library.
- Preventing the user from entering a value for the library volume less than the used volume.

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-04-19 15:06 UTC, BenTopping requested changes
Tested and looks really good. 

The forced minimum value is quite aggressive and it makes it quite tricky to change the volume as it doesn't let you delete values and retype easily. Can we debounce it or something or is that a tradeoff of using min?

2024-04-19 15:09 UTC, seenanair commented
> Tested and looks really good.
> 
> The forced minimum value is quite aggressive and it makes it quite tricky to change the volume as it doesn't let you delete values and retype easily. Can we debounce it or something or is that a tradeoff of using min?

Yes, you are right. I felt it us very forceful (this is what I mentioned in https://github.com/sanger/traction-service/pull/1288 comment). I will look into it. Probably we can have a chat about it next week.

2024-04-19 15:11 UTC, seenanair commented on src/components/pacbio/PacbioLibraryForm.vue
> +              :style="{ top: '-25px' }"
I tried, but didn't work. I think it needs bit more work with tailwind config update. I will check it again. 👍

2024-04-19 15:12 UTC, seenanair commented on src/components/pacbio/PacbioLibraryForm.vue
> +watch(
Unfortunately :min doesn't prevent user from typing in values directly into textfield. It only sets the min for the spinner control.

2024-04-22 13:54 UTC, BenTopping submitted a review, later dismissed
Looks good 👌

2024-04-23 12:31 UTC, BenTopping approved these changes

2024-04-23 12:58 UTC, merged