Removing better-docs because of security vulnerabilities
sanger/traction-ui pull request #1981
Opened 2024-09-30 07:15 UTC by dasunpubudumal

…sdoc.json configuration to remove the "better-docs" plugin.

Closes #

#### Changes proposed in this pull request

- 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-09-30 12:28 UTC, BenTopping requested changes
I think we need to run 'npm run jsdoc' to rebuild the docs after removing this plugin as this dependency affects the style of the docs. Do we have to remove this deps? Is there a link to the security issue created from it?

2024-09-30 12:29 UTC, dasunpubudumal commented
> I think we need to run 'npm run jsdoc' to rebuild the docs after removing this plugin.

Hi Ben, it's run on CI isn't it?

2024-09-30 12:45 UTC, stevieing approved these changes
We can check it on UAT to see how different it looks. I ran it locally and it looks ok.

We could always add our own styling template if it is terrible.

2024-10-02 08:05 UTC, BenTopping approved these changes

2024-10-02 08:23 UTC, BenTopping approved these changes

2024-10-02 08:24 UTC, merged