Y24 141 labwhere reception to scan tubes and plates into locations
sanger/traction-ui pull request #1986
Opened 2024-10-01 12:34 UTC by seenanair

Closes #

#### Changes proposed in this pull request

- Adds Labwhere reception page to store labwhere barcodes 
   - This includes a form interface for users to store labware barcodes into a specified location in Labwhere.
   -  The form includes fields for: User barcode or swipecard, Location barcode, Start position (optional), Labware barcodes
   - The component validates the input fields for 'User barcode', 'Location barcode' and 'Labware barcodes'
       and displays error messages for any invalid or missing data when the form is submitted or when the input fields are 
        updated.
   - The 'Start position' field is optional and does not require validation.
   -  Upon successful validation, the form data is submitted to the Labwhere API to store the barcodes in the specified 
         location.
   - It displays a success message if the barcodes are stored successfully, or an error message if the submission fails.

- Adds storeBarcodesIntoLabwhereLocation helper method for storing barcodes to Labwhere location using Labwhere 
   scans api
- Updates FetchWrapper class to have content_type parameter

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-10-02 13:19 UTC, BenTopping requested changes
Good start, tested locally and the page looks good and works well with nice error handling 👌 

Couple things:
- application/json should work as the content-type for the scans api. Ive tested locally with a basic CURL and seems to work so might be a setup issue for the CORS error.
- Im not sure the preview area of the page adds much. Maybe a text highlight in red for duplicate barcodes and an error preventing submission if there are duplicates would be better.
- A clear button to remove the labware location, position and barcodes might be useful if they are doing a lot of labware at once (not sure if this will happen but worth thinking about).

2024-10-02 13:19 UTC, BenTopping commented on tests/unit/views/LabWhereReception.spec.js
> +    const [userInput] = wrapper.findAll('input')
Worth using a test-id or data attribute to make input more discoverable?

2024-10-02 13:19 UTC, BenTopping commented on src/router.js
> +      meta: { page: 'Labwhere Reception - Scan In/Out' },
LabWhere*

2024-10-02 16:28 UTC, seenanair commented
> Good start, tested locally and the page looks good and works well with nice error handling 👌
> 
> Couple things:
> 
> * application/json should work as the content-type for the scans api. Ive tested locally with a basic CURL and seems to work so might be a setup issue for the CORS error.

Oh, interesting. I tried it many different ways, but never worked for me with CORS error.

> * Im not sure the preview area of the page adds much. Maybe a text highlight in red for duplicate barcodes and an error preventing submission if there are duplicates would be better.

Following was my thought to do a preview area. 'Labware count' is specified as a requirement by the stakeholder, and I believe it would be useful to display it as preview text. Additionally, since we are not validating against an empty location barcode, which could potentially cause a reverse effect (scanning out) on normal operations, it is important to display the intended action's purpose somewhere for confirmation.

> * A clear button to remove the labware location, position and barcodes might be useful if they are doing a lot of labware at once (not sure if this will happen but worth thinking about).
A 'Reset' button was initially there but in attempt to make it similar to LabWhere scan in page, I removed it.

2024-10-02 17:03 UTC, seenanair commented
> > Good start, tested locally and the page looks good and works well with nice error handling 👌
> > Couple things:
> > 
> > * application/json should work as the content-type for the scans api. Ive tested locally with a basic CURL and seems to work so might be a setup issue for the CORS error.
> 
> @BenTopping Oh, interesting. I tried it many different ways, but never worked for me with CORS error.
> 
> > * Im not sure the preview area of the page adds much. Maybe a text highlight in red for duplicate barcodes and an error preventing submission if there are duplicates would be better.
> 
> Following was my thought to do a preview area. 'Labware count' is specified as a requirement by the stakeholder, and I believe it would be useful to display it as preview text. Additionally, since we are not validating against an empty location barcode, which could potentially cause a reverse effect (scanning out) on normal operation of scanning in, thought it is important to display the intended action's purpose somewhere for confirmation.
> 
> > * A clear button to remove the labware location, position and barcodes might be useful if they are doing a lot of labware at once (not sure if this will happen but worth thinking about).
> 
> A 'Reset' button was initially there but in attempt to make it similar to LabWhere scan in page, I removed it. :)

2024-10-07 10:13 UTC, BenTopping approved these changes

2024-10-07 10:25 UTC, merged